# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :archive do |options|
    sync_code_signing(type: "development")
    update_code_signing_settings(use_automatic_signing: false)
    build_app(
      **options,
      scheme: "TweetNest (iOS)",
      skip_package_ipa: true,
      skip_package_pkg: true
    )
    update_code_signing_settings(use_automatic_signing: true)
  end

  lane :deploy_beta do
    export(export_method: "app-store")
    upload_to_testflight
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    archive
    deploy_beta
  end

  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "TweetNest.xcodeproj")
    build_app(scheme: "TweetNest (iOS)")
    upload_to_app_store
  end
  
  private_lane :export do |options|
    if options[:export_method] == "app-store"
      sync_code_signing(type: "appstore")
    elsif options[:export_method] == "development"
      sync_code_signing(type: "development")
    else
      sync_code_signing(type: "adhoc")
    end

    build_app(
      **options,
      scheme: "TweetNest (iOS)",
      skip_build_archive: true
    )
  end
end
